server:
  port: 12342

spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local
  application:
    name: ts-user-service
  datasource:
    url: jdbc:mysql://ts-user-mysql:3306/ts-user-mysql?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update


swagger:
  controllerPackage: user.controller

auth-service:
  url: http://${AUTH_SERVICE_HOST:ts-auth-service}:${AUTH_SERVICE_PORT:12340}