server:
  port: 19999

spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local
  application:
    name: ts-train-food-service
  datasource:
    url: jdbc:mysql://${DELIVERY_MYSQL_HOST:ts-train-food-mysql}:${DELIVERY_MYSQL_PORT:3306}/${DELIVERY_MYSQL_DATABASE:ts-train-food-mysql}?useSSL=false
    username: ${DELIVERY_MYSQL_USER:root}
    password: ${DELIVERY_MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

swagger:
  controllerPackage: trainFood.controller