server:
  port: 18855

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local}
  application:
    name: ts-station-food-service
  datasource:
#    url: jdbc:mysql://10.176.122.80:32005/ts-station-food-mysql?useSSL=false
    url: jdbc:mysql://${STATION_FOOD_MYSQL_HOST:ts-station-food-mysql}:${STATION_FOOD_MYSQL_PORT:3306}/${STATION_FOOD_MYSQL_DATABASE:ts-station-food-mysql}?useSSL=false
    username: ${STATION_FOOD_MYSQL_USER:root}
    password: ${STATION_FOOD_MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update

swagger:
  controllerPackage: food.controller